[project]
name = "driving"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.1",
    "opencv-python>=5.0.0.93",
    "pandas>=3.0.5",
    "scipy>=1.18.1",
    "torch>=2.14.0",
    "torchvision>=0.29.0",
    "ultralytics>=8.4.146",
]

[tool.uv.sources]
torch = [{ index = "pytorch-cpu" }]
torchvision = [{ index = "pytorch-cpu" }]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
